using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace ApartYonetim
{
    public partial class frmMusteriEkleme : DevExpress.XtraEditors.XtraForm
    {
        List<tbl_Binalar> binalar;
        tbl_Daireler daire = new tbl_Daireler();
        List<tbl_Daireler> daireler;
        int selectedDaireNo;
        public frmMusteriEkleme()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            daireler = daire.Listele().ToList(); 
        }

        private void tbl_MusterilerBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();


        }

        private void frmMusteriEkleme_Load(object sender, EventArgs e)
        {  
            // TODO: This line of code loads data into the 'aYSDataSet.tbl_Musteriler' table. You can move, or remove it, as needed.
            this.tbl_MusterilerTableAdapter.Fill(this.aYSDataSet.tbl_Musteriler);
            // TODO: This line of code loads data into the 'aYSDataSet.spMusteriDaireBina' table. You can move, or remove it, as needed.
            this.spMusteriDaireBinaTableAdapter.Fill(this.aYSDataSet.spMusteriDaireBina);
            tbl_Binalar bina = new tbl_Binalar();
            binalar = bina.Listele().ToList();
          
            foreach (tbl_Binalar binaAdi in binalar)
            {
                bina_adiComboBox.Items.Add(binaAdi.Bina_adi);
            }
        }

        private void musteri_durumuLabel_Click(object sender, EventArgs e)
        {

        }

        private void btnYeni_Click(object sender, EventArgs e)
        {
            AlanEnabled(true);
            AlanBosalt();
            musteri_tc_kimlik_noTextEdit.Focus();
        }
        private void AlanEnabled(bool islem)
        {
            groupMusteri.Enabled = islem;
            btnYeni.Enabled = !islem;
            btnSil.Enabled = !islem;
            btnGuncelle.Enabled = !islem;
            btnVazgec.Enabled = islem;
            btnKaydet.Enabled = islem;
            gcMusteriler.Enabled = !islem;

        }
        private void AlanBosalt()
        {
            musteri_adiTextEdit.Text = "";
            musteri_aciklamaTextEdit.Text = "";
            musteri_adresTextEdit.Text = "";
            musteri_durumuCheckEdit.Checked = false;
            musteri_emailTextEdit.Text = "";
            musteri_kira_tutariSpinEdit.Text = "";
            musteri_sehirTextEdit.Text = "";
            musteri_soyadiTextEdit.Text = "";
            musteri_tc_kimlik_noTextEdit.Text = "";
            musteri_telefon_noTextEdit.Text = "";
            musteri_telefon_no2TextEdit.Text = "";
            musteri_yetkiCheckEdit.Checked = false;
            musteri_kontrat_baslangic_tarihiDateEdit.DateTime = DateTime.Now;
            musteri_kontrat_bitis_tarihiDateEdit.DateTime = DateTime.Now;

        }

        private void btnVazgec_Click(object sender, EventArgs e)
        {
            AlanEnabled(false);
        }

        private void btnKaydet_Click(object sender, EventArgs e)
        {

            try
            {
                tbl_Musteriler musteri = new tbl_Musteriler();
                musteri.Musteri_adi = musteri_adiTextEdit.Text;
                musteri.Musteri_soyadi = musteri_soyadiTextEdit.Text;
                musteri.Musteri_tc_kimlik_no = musteri_tc_kimlik_noTextEdit.Text;
                musteri.Musteri_telefon_no = musteri_telefon_noTextEdit.Text;
                musteri.Musteri_telefon_no2 = musteri_telefon_no2TextEdit.Text;
                musteri.Musteri_sehir = musteri_sehirTextEdit.Text;
                musteri.Musteri_adres = musteri_adresTextEdit.Text;
                musteri.Musteri_kira_tutari = (float)Convert.ToDouble(musteri_kira_tutariSpinEdit.Text);
                musteri.Musteri_email = musteri_emailTextEdit.Text;
                musteri.Daire_no = selectedDaireNo;
                musteri.Musteri_aciklama = musteri_aciklamaTextEdit.Text;
                musteri.Musteri_kayit_tarihi = DateTime.Now;
                musteri.Musteri_duzenleme_tarihi = DateTime.Now;
                musteri.Musteri_kontrat_baslangic_tarihi = musteri_kontrat_baslangic_tarihiDateEdit.DateTime;
                musteri.Musteri_kontrat_bitis_tarihi = musteri_kontrat_bitis_tarihiDateEdit.DateTime;
                musteri.Musteri_yetki = musteri_yetkiCheckEdit.Checked;
                musteri.Musteri_durumu = true;
                musteri.Musteri_kayit_eden_yonetici_id = 1;
                int sonuc = musteri.YeniKaydet(musteri);
                if (sonuc == 1)
                    MessageBox.Show("Kayıt başarılı");
                else
                    MessageBox.Show("Kayıt başarısız");

            }
            catch (Exception ex)
            {
                MessageBox.Show("Kayıt başarısız \r\n"+ex.Message);
            }
        }
        List<tbl_Daireler> binayaAitDaireler;
        private void bina_adiComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            binayaAitDaireler = new List<tbl_Daireler>();
            string binaAdi = bina_adiComboBox.SelectedItem.ToString();
            int binaId=0;
            daire_noComboBox.Items.Clear();
            daire_noComboBox.Text = "";
            foreach (tbl_Binalar bina in binalar)
            {
                if (binaAdi == bina.Bina_adi)
                    binaId = bina.Bina_id;
            }
            foreach(tbl_Daireler tempDaire in daireler)
            {
                if (tempDaire.Bina_id == binaId)
                {
                    binayaAitDaireler.Add(tempDaire);
                    daire_noComboBox.Items.Add(tempDaire.Daire_kapi_no);
                }
            }
        }

        private void daire_noComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            foreach(tbl_Daireler daire in binayaAitDaireler)
            {
                if(daire.Daire_kapi_no==Convert.ToInt32(daire_noComboBox.SelectedItem.ToString()))
                {
                    selectedDaireNo = daire.Daire_no;
                    break;
                }
            }
        }

        private void btnGuncelle_Click(object sender, EventArgs e)
        {
            try
            {
                tbl_Musteriler musteri = new tbl_Musteriler();
                musteri.Musteri_adi = musteri_adiTextEdit.Text;
                musteri.Musteri_soyadi = musteri_soyadiTextEdit.Text;
                musteri.Musteri_tc_kimlik_no = musteri_tc_kimlik_noTextEdit.Text;
                musteri.Musteri_telefon_no = musteri_telefon_noTextEdit.Text;
                musteri.Musteri_telefon_no2 = musteri_telefon_no2TextEdit.Text;
                musteri.Musteri_sehir = musteri_sehirTextEdit.Text;
                musteri.Musteri_adres = musteri_adresTextEdit.Text;
                musteri.Musteri_kira_tutari = (float)Convert.ToDouble(musteri_kira_tutariSpinEdit.Text);
                musteri.Musteri_email = musteri_emailTextEdit.Text;
                musteri.Daire_no = selectedDaireNo;
                musteri.Musteri_aciklama = musteri_aciklamaTextEdit.Text;
                musteri.Musteri_duzenleme_tarihi = DateTime.Now;
                musteri.Muster_kayit_duzenleyen_yonetici_id = 1;
                musteri.Musteri_kontrat_baslangic_tarihi = musteri_kontrat_baslangic_tarihiDateEdit.DateTime;
                musteri.Musteri_kontrat_bitis_tarihi = musteri_kontrat_bitis_tarihiDateEdit.DateTime;
                musteri.Musteri_yetki = musteri_yetkiCheckEdit.Checked;
                musteri.Musteri_durumu = true;
                musteri.Musteri_kayit_eden_yonetici_id = 1;
                int sonuc= musteri.Guncelle(musteri);
                if (sonuc == 1)
                    MessageBox.Show("Güncelleme başarılı");
                else
                    MessageBox.Show("Güncelleme başarısız");

            }
            catch (Exception ex)
            {
                MessageBox.Show("Güncelleme başarısız \r\n" + ex.Message);
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
          bina_adiComboBox.Text = gridView1.GetFocusedRowCellValue("Apart Adı").ToString();
            daire_noComboBox.Text = gridView1.GetFocusedRowCellValue("Daire Kapı No").ToString();
        }
    }
}